import type { NextPage } from 'next';
import Head from 'next/head';
import { NavBar } from '../components';
import { trpc } from '../utils/trpc';

const Home: NextPage = () => {
  const hello = trpc.example.hello.useQuery({ text: 'from tRPC' });
  console.log(hello.data?.greeting);
  return (
    <>
      <div>
        <Head>
          <title>Prakhar Portfolio</title>
          <meta name='description' content='Generated by create next app' />
          <link rel='icon' href='/favicon.ico' />
        </Head>
        <main>
          <NavBar />
          <div className='my-40 flex justify-center'>
            <div className='animate-shine break-words bg-gradient-to-r from-cyan-300 to-sky-500 bg-clip-text text-center text-5xl font-semibold text-transparent md:text-7xl lg:text-8xl'>
              Prakhar Goel
            </div>
          </div>
        </main>
      </div>
    </>
  );
};

export default Home;
