import type { NextPage } from 'next';
import Head from 'next/head';
import { NavBar } from '../components';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Prakhar Portfolio</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>
        <NavBar />
        <div className='my-40 flex justify-center'>
          <div className='lg:text-8xl md:text-7xl text-5xl bg-gradient-to-r from-cyan-300 to-sky-500 bg-clip-text text-transparent font-semibold animate-shine break-words text-center'>
            Prakhar Goel
          </div>
        </div>
      </main>
    </div>
  );
};

export default Home;
