import type { NextPage } from 'next';
import Head from 'next/head';
import { NavBar } from '../Components';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Prakhar Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <NavBar />
        <div className="my-40 flex justify-center">
          <h1 className="text-8xl bg-gradient-to-r from-cyan-300 to-sky-500 bg-clip-text text-transparent font-semibold animate-shine break-words text-center">
            Prakhar Goel
          </h1>
        </div>
      </main>
    </div>
  );
};

export default Home;
